services:
  node-server:
    build: .
    command: npm run dev
    ports:
      - "4242:4242"
    restart: always
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - PG_USER=user
      - PG_PASSWORD=password

  database:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=smart
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
